#!/usr/bin/python3

import sys

def checkOperation(operation: str) -> bool:
    valid = "0123456789+-*/%()."
    for c in operation:
        if c not in valid:
            return False
    return True

calc = str(input())
if checkOperation(calc) is False:
    sys.exit(84)
else:
    print(eval(calc))
    sys.exit(0)
