#!/usr/bin/ruby

def validOperation(operation)
  String valid = "0123456789+-/*%()."
  operation.each_char { |c|
    return FALSE if not valid.include? c
  }
  return TRUE
end

loop do
  input = gets
  break if input.nil?
  input = "0" if not validOperation input.chomp
  print "#{eval(input)}\n"
end
